# Report Columns Configuration
REPORT_COLUMNS = {
    "employee_info": [
        {"key": "employee_id", "label": "Employee ID", "type": "string"},
        {"key": "first_name", "label": "First Name", "type": "string"},
        {"key": "last_name", "label": "Last Name", "type": "string"},
        {"key": "email", "label": "Email", "type": "string"},
        {"key": "department", "label": "Department", "type": "string"},
        {"key": "team", "label": "Team", "type": "string"},
        {"key": "job_title", "label": "Job Title", "type": "string"},
        {"key": "job_level", "label": "Job Level", "type": "string"},
        {"key": "location", "label": "Location", "type": "string"},
        {"key": "work_type", "label": "Work Type", "type": "string"},
        {"key": "status", "label": "Status", "type": "string"},
        {"key": "manager_name", "label": "Manager", "type": "string"},
    ],
    "compensation": [
        {"key": "salary", "label": "Salary", "type": "number"},
        {"key": "currency", "label": "Currency", "type": "string"},
        {"key": "bonus_target", "label": "Bonus Target %", "type": "number"},
        {"key": "cost_per_hire", "label": "Cost Per Hire", "type": "number"},
    ],
    "demographics": [
        {"key": "age", "label": "Age", "type": "number"},
        {"key": "gender", "label": "Gender", "type": "string"},
        {"key": "ethnicity", "label": "Ethnicity", "type": "string"},
    ],
    "dates": [
        {"key": "hire_date", "label": "Hire Date", "type": "date"},
        {"key": "termination_date", "label": "Termination Date", "type": "date"},
        {"key": "last_review_date", "label": "Last Review Date", "type": "date"},
        {"key": "last_promotion_date", "label": "Last Promotion Date", "type": "date"},
    ],
    "performance": [
        {"key": "performance_rating", "label": "Performance Rating", "type": "number"},
        {"key": "engagement_score", "label": "Engagement Score", "type": "number"},
        {"key": "training_hours", "label": "Training Hours", "type": "number"},
        {"key": "tenure", "label": "Tenure (Years)", "type": "number"},
        {"key": "quality_of_hire_score", "label": "Quality of Hire", "type": "number"},
        {"key": "flight_risk", "label": "Flight Risk", "type": "string"},
    ],
    "source": [
        {"key": "previous_company", "label": "Previous Company", "type": "string"},
        {"key": "reason_for_leaving", "label": "Reason for Leaving", "type": "string"},
        {"key": "source_system", "label": "Source System", "type": "string"},
    ],
}

# Country Holiday Data (2026)
COUNTRY_HOLIDAYS = {
    "US": {
        "name": "United States",
        "default_pto_days": 15,
        "holidays": [
            {"date": "2026-01-01", "name": "New Year's Day"},
            {"date": "2026-01-19", "name": "Martin Luther King Jr. Day"},
            {"date": "2026-02-16", "name": "Presidents' Day"},
            {"date": "2026-05-25", "name": "Memorial Day"},
            {"date": "2026-07-03", "name": "Independence Day (Observed)"},
            {"date": "2026-09-07", "name": "Labor Day"},
            {"date": "2026-10-12", "name": "Columbus Day"},
            {"date": "2026-11-11", "name": "Veterans Day"},
            {"date": "2026-11-26", "name": "Thanksgiving"},
            {"date": "2026-12-25", "name": "Christmas Day"},
        ]
    },
    "GB": {
        "name": "United Kingdom",
        "default_pto_days": 28,
        "holidays": [
            {"date": "2026-01-01", "name": "New Year's Day"},
            {"date": "2026-04-03", "name": "Good Friday"},
            {"date": "2026-04-06", "name": "Easter Monday"},
            {"date": "2026-05-04", "name": "Early May Bank Holiday"},
            {"date": "2026-05-25", "name": "Spring Bank Holiday"},
            {"date": "2026-08-31", "name": "Summer Bank Holiday"},
            {"date": "2026-12-25", "name": "Christmas Day"},
            {"date": "2026-12-28", "name": "Boxing Day (Observed)"},
        ]
    },
    "CA": {
        "name": "Canada",
        "default_pto_days": 15,
        "holidays": [
            {"date": "2026-01-01", "name": "New Year's Day"},
            {"date": "2026-02-16", "name": "Family Day"},
            {"date": "2026-04-03", "name": "Good Friday"},
            {"date": "2026-05-18", "name": "Victoria Day"},
            {"date": "2026-07-01", "name": "Canada Day"},
            {"date": "2026-08-03", "name": "Civic Holiday"},
            {"date": "2026-09-07", "name": "Labour Day"},
            {"date": "2026-10-12", "name": "Thanksgiving"},
            {"date": "2026-12-25", "name": "Christmas Day"},
        ]
    },
    "DE": {
        "name": "Germany",
        "default_pto_days": 25,
        "holidays": [
            {"date": "2026-01-01", "name": "New Year's Day"},
            {"date": "2026-04-03", "name": "Good Friday"},
            {"date": "2026-04-06", "name": "Easter Monday"},
            {"date": "2026-05-01", "name": "Labour Day"},
            {"date": "2026-05-14", "name": "Ascension Day"},
            {"date": "2026-05-25", "name": "Whit Monday"},
            {"date": "2026-12-25", "name": "Christmas Day"},
            {"date": "2026-12-26", "name": "Second Christmas Day"},
        ]
    },
    "AU": {
        "name": "Australia",
        "default_pto_days": 20,
        "holidays": [
            {"date": "2026-01-01", "name": "New Year's Day"},
            {"date": "2026-01-26", "name": "Australia Day"},
            {"date": "2026-04-03", "name": "Good Friday"},
            {"date": "2026-04-04", "name": "Saturday before Easter Sunday"},
            {"date": "2026-04-06", "name": "Easter Monday"},
            {"date": "2026-04-25", "name": "ANZAC Day"},
            {"date": "2026-06-08", "name": "Queen's Birthday"},
            {"date": "2026-12-25", "name": "Christmas Day"},
            {"date": "2026-12-26", "name": "Boxing Day"},
        ]
    },
    "IN": {
        "name": "India",
        "default_pto_days": 18,
        "holidays": [
            {"date": "2026-01-26", "name": "Republic Day"},
            {"date": "2026-03-10", "name": "Holi"},
            {"date": "2026-04-02", "name": "Ram Navami"},
            {"date": "2026-04-03", "name": "Good Friday"},
            {"date": "2026-05-01", "name": "May Day"},
            {"date": "2026-08-15", "name": "Independence Day"},
            {"date": "2026-10-02", "name": "Gandhi Jayanti"},
            {"date": "2026-10-20", "name": "Dussehra"},
            {"date": "2026-11-09", "name": "Diwali"},
            {"date": "2026-12-25", "name": "Christmas Day"},
        ]
    },
    "JP": {
        "name": "Japan",
        "default_pto_days": 10,
        "holidays": [
            {"date": "2026-01-01", "name": "New Year's Day"},
            {"date": "2026-01-12", "name": "Coming of Age Day"},
            {"date": "2026-02-11", "name": "National Foundation Day"},
            {"date": "2026-02-23", "name": "Emperor's Birthday"},
            {"date": "2026-03-20", "name": "Vernal Equinox Day"},
            {"date": "2026-04-29", "name": "Showa Day"},
            {"date": "2026-05-03", "name": "Constitution Memorial Day"},
            {"date": "2026-05-04", "name": "Greenery Day"},
            {"date": "2026-05-05", "name": "Children's Day"},
            {"date": "2026-07-20", "name": "Marine Day"},
            {"date": "2026-09-21", "name": "Respect for the Aged Day"},
            {"date": "2026-09-23", "name": "Autumnal Equinox Day"},
            {"date": "2026-10-12", "name": "Sports Day"},
            {"date": "2026-11-03", "name": "Culture Day"},
            {"date": "2026-11-23", "name": "Labour Thanksgiving Day"},
        ]
    },
    "SG": {
        "name": "Singapore",
        "default_pto_days": 14,
        "holidays": [
            {"date": "2026-01-01", "name": "New Year's Day"},
            {"date": "2026-01-29", "name": "Chinese New Year"},
            {"date": "2026-01-30", "name": "Chinese New Year (Day 2)"},
            {"date": "2026-04-03", "name": "Good Friday"},
            {"date": "2026-05-01", "name": "Labour Day"},
            {"date": "2026-05-26", "name": "Vesak Day"},
            {"date": "2026-06-24", "name": "Hari Raya Haji"},
            {"date": "2026-08-09", "name": "National Day"},
            {"date": "2026-10-20", "name": "Deepavali"},
            {"date": "2026-12-25", "name": "Christmas Day"},
        ]
    },
    "BR": {
        "name": "Brazil",
        "default_pto_days": 30,
        "holidays": [
            {"date": "2026-01-01", "name": "New Year's Day"},
            {"date": "2026-02-16", "name": "Carnival"},
            {"date": "2026-02-17", "name": "Carnival (Day 2)"},
            {"date": "2026-04-03", "name": "Good Friday"},
            {"date": "2026-04-21", "name": "Tiradentes Day"},
            {"date": "2026-05-01", "name": "Labour Day"},
            {"date": "2026-06-04", "name": "Corpus Christi"},
            {"date": "2026-09-07", "name": "Independence Day"},
            {"date": "2026-10-12", "name": "Our Lady of Aparecida"},
            {"date": "2026-11-02", "name": "All Souls' Day"},
            {"date": "2026-11-15", "name": "Republic Proclamation Day"},
            {"date": "2026-12-25", "name": "Christmas Day"},
        ]
    },
    "MX": {
        "name": "Mexico",
        "default_pto_days": 12,
        "holidays": [
            {"date": "2026-01-01", "name": "New Year's Day"},
            {"date": "2026-02-02", "name": "Constitution Day"},
            {"date": "2026-03-16", "name": "Benito Juárez's Birthday"},
            {"date": "2026-05-01", "name": "Labour Day"},
            {"date": "2026-09-16", "name": "Independence Day"},
            {"date": "2026-11-16", "name": "Revolution Day"},
            {"date": "2026-12-25", "name": "Christmas Day"},
        ]
    },
    "ES": {
        "name": "Spain",
        "default_pto_days": 22,
        "holidays": [
            {"date": "2026-01-01", "name": "New Year's Day"},
            {"date": "2026-01-06", "name": "Epiphany"},
            {"date": "2026-04-03", "name": "Good Friday"},
            {"date": "2026-05-01", "name": "Labour Day"},
            {"date": "2026-08-15", "name": "Assumption of Mary"},
            {"date": "2026-10-12", "name": "National Day"},
            {"date": "2026-11-01", "name": "All Saints' Day"},
            {"date": "2026-12-06", "name": "Constitution Day"},
            {"date": "2026-12-08", "name": "Immaculate Conception"},
            {"date": "2026-12-25", "name": "Christmas Day"},
        ]
    },
}

# Currency Configuration
CURRENCIES = [
    {"code": "EUR", "name": "Euro", "symbol": "€"},
    {"code": "USD", "name": "US Dollar", "symbol": "$"},
    {"code": "GBP", "name": "British Pound", "symbol": "£"},
    {"code": "AED", "name": "UAE Dirham", "symbol": "د.إ"},
    {"code": "ARS", "name": "Argentine Peso", "symbol": "$"},
    {"code": "AUD", "name": "Australian Dollar", "symbol": "A$"},
    {"code": "BRL", "name": "Brazilian Real", "symbol": "R$"},
    {"code": "CAD", "name": "Canadian Dollar", "symbol": "C$"},
    {"code": "CHF", "name": "Swiss Franc", "symbol": "CHF"},
    {"code": "CLP", "name": "Chilean Peso", "symbol": "$"},
    {"code": "CNY", "name": "Chinese Yuan", "symbol": "¥"},
    {"code": "COP", "name": "Colombian Peso", "symbol": "$"},
    {"code": "CRC", "name": "Costa Rican Colon", "symbol": "₡"},
    {"code": "CZK", "name": "Czech Koruna", "symbol": "Kč"},
    {"code": "DKK", "name": "Danish Krone", "symbol": "kr"},
    {"code": "EGP", "name": "Egyptian Pound", "symbol": "E£"},
    {"code": "HKD", "name": "Hong Kong Dollar", "symbol": "HK$"},
    {"code": "HUF", "name": "Hungarian Forint", "symbol": "Ft"},
    {"code": "IDR", "name": "Indonesian Rupiah", "symbol": "Rp"},
    {"code": "ILS", "name": "Israeli Shekel", "symbol": "₪"},
    {"code": "INR", "name": "Indian Rupee", "symbol": "₹"},
    {"code": "JPY", "name": "Japanese Yen", "symbol": "¥"},
    {"code": "KES", "name": "Kenyan Shilling", "symbol": "KSh"},
    {"code": "KRW", "name": "South Korean Won", "symbol": "₩"},
    {"code": "MXN", "name": "Mexican Peso", "symbol": "$"},
    {"code": "MYR", "name": "Malaysian Ringgit", "symbol": "RM"},
    {"code": "NGN", "name": "Nigerian Naira", "symbol": "₦"},
    {"code": "NOK", "name": "Norwegian Krone", "symbol": "kr"},
    {"code": "NZD", "name": "New Zealand Dollar", "symbol": "NZ$"},
    {"code": "PEN", "name": "Peruvian Sol", "symbol": "S/."},
    {"code": "PHP", "name": "Philippine Peso", "symbol": "₱"},
    {"code": "PLN", "name": "Polish Zloty", "symbol": "zł"},
    {"code": "QAR", "name": "Qatari Riyal", "symbol": "﷼"},
    {"code": "RON", "name": "Romanian Leu", "symbol": "lei"},
    {"code": "SAR", "name": "Saudi Riyal", "symbol": "﷼"},
    {"code": "SEK", "name": "Swedish Krona", "symbol": "kr"},
    {"code": "SGD", "name": "Singapore Dollar", "symbol": "S$"},
    {"code": "THB", "name": "Thai Baht", "symbol": "฿"},
    {"code": "TRY", "name": "Turkish Lira", "symbol": "₺"},
    {"code": "TWD", "name": "Taiwan Dollar", "symbol": "NT$"},
    {"code": "VND", "name": "Vietnamese Dong", "symbol": "₫"},
    {"code": "ZAR", "name": "South African Rand", "symbol": "R"},
]
